listen = "0.0.0.0:234"
database_path = "data/reader.sqlite"
library_dirs = ["C:\\Users\\Administrator\\Music\\rust\\n\\logs"]
scan_recursive = false
scan_on_startup = false
tls_cert_path = "certs/server-cert.pem"
tls_key_path = "certs/server-key.pem"
