listen = "0.0.0.0:234"
database_path = "data/reader.sqlite"
library_dirs = ["E:\\Videos\\小说"]
scan_recursive = true
scan_on_startup = false
tls_cert_path = "certs/server-cert.pem"
tls_key_path = "certs/server-key.pem"
